In [38]:
import autograd.numpy as np
from autograd import grad
from all_functions.objective_function import sigmoid

def f(x):
    return np.linalg.norm(x)**2
# f = lambda z: np.linalg.norm(y-np.dot(A, z[:n]-z[n:]), 2)**2
# f = lambda z: np.linalg.norm(y-np.dot(A, z[:n]-z[n:]), 2)**2
grad_f = grad(f)

x = np.array([[1.0],
              [1.0]])
grad_f(x)
# print(grad_f(np.array([[1],
#                       [2]])))

A = np.array([[1, 2],
              [3, 4]])
b = np.array([[-1],
              [+1]]).flatten()


def chat_gpt(x):
    logits = (A.dot(x)) * b
    return float(np.mean(np.logaddexp(0, -logits)))

def cyrille(x):
    return np.mean(np.log(1+np.exp(-b.flatten()*(np.dot(A, x).flatten()))))


def chat_gpt_grad(x: np.ndarray):
    """Evaluates the gradient of f at x."""
    logits = A.dot(x) * b.flatten()
    probs = sigmoid(-logits)
    grad = A.T.dot(-b * probs) / A.shape[0]
    return grad

def cyrille_grad(x):
    grad_c = grad(cyrille)
    return grad_c(x)


print(chat_gpt(x))
print(cyrille(x))
print(chat_gpt_grad(x.flatten()))
print(cyrille_grad(x))


2.5247494090137583
1.524749409013758
[0.47492049 0.95075202]
[[0.47492049]
 [0.95075202]]


In [39]:
logits = self.A.dot(x) * self.b
return float(np.mean(np.logaddexp(0, -logits)))




NameError: name 'self' is not defined

In [46]:
import urllib.request

def load_gisette_data():

    # Load the data files into numpy arrays
    X = np.loadtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/gisette/GISETTE/gisette_train.data')
    y = np.loadtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/gisette/GISETTE/gisette_train.labels')

    return X, y
X,y = load_gisette_data()

In [47]:
print(X, y)



[[550.   0. 495. ...   0.   0. 983.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 991. ...   0.   0. 991.]] [ 1. -1.  1. ... -1. -1. -1.]


In [48]:


np.nan_to_num(nan)

NameError: name 'nan' is not defined